name: uniprint
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.4
  simple_speed_dial: ^0.1.2
  sprintf: ^4.0.2
  pdf_render: ^0.57.1
  device_info: ^0.4.1+5
  sentry: ^3.0.1
  hive_flutter: ^0.3.0+1
  hive: ^1.4.0+1
  timeline_list: ^0.0.5 
  hasura_connect: ^1.2.2+1
  #hasura_connect: ^1.0.3
  flutter_mobx: ^0.3.4+3
  mobx: ^0.3.6
  dio: ^3.0.8
  rxdart: ^0.23.1
  bloc_pattern: ^2.5.1

  cloud_firestore: ^0.12.7

  firebase_auth: ^0.14.0
  firebase_storage: ^3.0.6
  firebase_messaging: ^5.1.5
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  json_annotation: ^2.0.0

  masked_text: ^0.0.6
  http: any
  json_serializable: ^2.0.0
  flutter_staggered_grid_view: "^0.3.0"

  #seletor de arquivos
  file_picker: ^1.4.0
   
  #number pic
  numberpicker: any
  #qrview
  qr_flutter: ^3.0.1
  #ler qrcode
  #qrcode_reader: ^0.4.4
  #formatar datas
  intl: ^0.16.0
  #notificacoes
  flutter_local_notifications: ^0.8.3
  #salvar chave-valor
  shared_preferences: ^0.5.3+4
  #progressDialog
  progress_dialog: ^1.2.0
  #animacao
  flutter_spinkit: "^4.0.0"
  #Grapql
  #banco de dados
  floor: ^0.9.0
  #starts
  smooth_star_rating: 1.0.3

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  hive_generator: ^0.7.0+2
  mobx_codegen: ^0.3.11
  build_runner: ^1.7.2
  mockito: ^4.1.1
  #flutter_test:
   # sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - imagens/


scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  createModule: slidy generate m modules/login -c
  compilar: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
